name: Deploy FPHY

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run docs:build

      - name: Deploy to Codeberg Pages
        uses: https://github.com/peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
          publish_branch: pages
          force_orphan: true